[package]
name = "theflate"
version = "0.1.0"
edition = "2021"

[lib]
name = "theflate"
path = "src/lib.rs"

[[bin]]
name = "theflate"
path = "src/main.rs"

[dev-dependencies]
tempfile = "3"

[dependencies]
glideapi = { path = "../glideapi" }
glideapi_macros = { path = "../glideapi/glideapi_macros" }
linkme = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
rusqlite = { version = "0.31", features = ["bundled"] }
uuid = { version = "1.8", features = ["v4"] }
rand = "0.8"
sha2 = "0.10"
hmac = "0.12"
hex = "0.4"
tracing = "0.1"
tracing-subscriber = "0.3"
libc = "0.2"
reqwest = { version = "0.12", features = ["json", "stream"] }
tokio-tungstenite = { version = "0.24", features = ["native-tls"] }
futures-util = "0.3"
tokio-util = { version = "0.7", features = ["io"] }
bytes = "1"
dotenvy = "0.15"
aws-sdk-s3 = "1"
aws-config = "1"
